### ISSUE TITLE
Capture exceptions when variables are not set

### ISSUE THREAD

**Issue by jlk** [snicholson-qualys/container_vuln_csv#1]
If the API username is not set in `QUALYS_API_USERNAME`, then the script crashes with an unhandled error:

```
Traceback (most recent call last):
  File "./container_vuln_cs.py", line 366, in <module>
    image_vuln_csv()
  File "./container_vuln_cs.py", line 68, in image_vuln_csv
    username, password, vuln_rating, URL = config()
  File "./container_vuln_cs.py", line 38, in config
    username = os.environ["QUALYS_API_USERNAME"]
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'QUALYS_API_USERNAME'
```

Would be nice to capture these and return a cleaner error

**Comment by snicholson-qualys** [comment]
updated config() for catching both KeyError for env variable and ./config.yml, and made check for API URL not left to default "<QUALYS_API_URL>"
